### ISSUE TITLE
Error importing tiff image

### ISSUE THREAD

**Issue by LiRenping199603** [argunsah/SpineS#5] opened 2022-03-23 03:48 UTC
Here are information from Command Window:
TiffDelegateReader initializing D:\���\SpineS-master\Tomato1.tif

Reading IFDs

Populating metadata

Checking comment style

Populating OME metadata

Reading series #1
    ........................................................................
    ...................
Signal Processing Toolbox is necessaryIndex in position 1 exceeds array bounds (must not exceed 162).
Error in cropAfterCircularShift3D (line 85)
imCropped = imStack(y1:y2,x1:x2,:);
Error in SpineS>ImportUsingBioformats_Callback (line 369)
     IcubeCropped  =
     padarray(cropAfterCircularShift3D(Icube,maxx,maxy,minx,miny),[handles.padValue,handles.padValue],round(median(Icube(:))/2),'both');
     Error in gui_mainfcn (line 95)
        feval(varargin{:});
Error in SpineS (line 77)
    gui_mainfcn(gui_State, varargin{:});
Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)SpineS('ImportUsingBioformats_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

**Comment by argunsah** [comment] 2022-03-24 11:11
Hello,
Can you share the data, so I can test and add a new function for you if necessary?
Best,
Ali

**Comment by LiRenping199603** [comment] 2022-03-24 11:35
Thank you for your help！hope the error will be fixed.
[Tomato_images.zip](https://github.com/argunsah/SpineS/files/8341050/Tomato_images.zip)

**Comment by argunsah** [comment] 2022-03-25 09:48
This file is not working. Can you try to download yourself to see the issue?

**Comment by argunsah** [comment] 2022-04-01 09:24
Hello, Are you going to share a working version of this dataset? Otherwise I will close this issue. Best.

**Comment by LiRenping199603** [comment] 2022-04-01 09:32
[Tomato_images.zip](https://github.com/argunsah/SpineS/files/8396508/Tomato_images.zip)
ok，I'll try again

**Comment by argunsah** [comment] 2022-04-01 11:10
The problem is your first image is 567x81 and your second image is 568x81 , 1-pixel bigger. All images has to be exactly same X and Y sizes (Z can change). You can resize your images accordingly and run the code again and it should work. 

However, I also realized that your images look very different, the data should be time series of the same dendrite.  it might work if you analyze them one by one rather than uploading them all at the same time.

**Closed as completed** 2022-04-05 13:34 UTC
